# Config Service
apiVersion: apps/v1
kind: Deployment
metadata:
    name: config-service-deployment
    labels:
        app: config-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: config-service
    template:
        metadata:
            labels:
                app: config-service
        spec:
            containers:
                - name: config-service
                  image: matiasfc/tingeso2_config_service:latest
                  ports:
                      - containerPort: 8081

---
# Servicio de Config Service
apiVersion: v1
kind: Service
metadata:
  name: config-service
spec:
  selector:
    app: config-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081