# Servicio de Eureka Service
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
spec:
  type: LoadBalancer
  selector:
    app: eureka-service
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761

---
# Servicio de Gateway Service
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: LoadBalancer
  selector:
    app: gateway-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
# BD Proveedores
apiVersion: v1
kind: Service
metadata:
  name: proveedor-db-service
spec:
  selector:
    app: proveedor-postgresdb
  ports:   
  - protocol: TCP
    port: 5432

---
# BD Acopio Leche
apiVersion: v1
kind: Service
metadata:
  name: acopio-leche-db-service
spec:
  selector:
    app: acopio-leche-postgresdb
  ports:   
  - protocol: TCP
    port: 5432

---
# BD Laboratorio Leche
apiVersion: v1
kind: Service
metadata:
  name: laboratorio-leche-db-service
spec:
  selector:
    app: laboratorio-leche-postgresdb
  ports:   
  - protocol: TCP
    port: 5432

---
# BD Pagos
apiVersion: v1
kind: Service
metadata:
  name: pago-db-service
spec:
  selector:
    app: pago-postgresdb
  ports:   
  - protocol: TCP
    port: 5432

---
# Proveedor Service
apiVersion: v1
kind: Service
metadata:
  name: proveedor-service
spec:
  selector:
    app: proveedor-service
  ports:   
  - protocol: TCP
    port: 8001

---
# Acopio Leche Service
apiVersion: v1
kind: Service
metadata:
  name: acopio-leche-service
spec:
  selector:
    app: acopio-leche-service
  ports:   
  - protocol: TCP
    port: 8002

---
# Laboratorio Leche Service
apiVersion: v1
kind: Service
metadata:
  name: laboratorio-leche-service
spec:
  selector:
    app: laboratorio-leche-service
  ports:   
  - protocol: TCP
    port: 8003

---
# Pago Service
apiVersion: v1
kind: Service
metadata:
  name: pago-service
spec:
  selector:
    app: pago-service
  ports:   
  - protocol: TCP
    port: 8004
